// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Akka.Interfaced CodeGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using EntityNetwork;
using ProtoBuf;
using TrackableData;
using TypeAlias;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Runtime.Serialization;
using ProtoBuf;
using TypeAlias;
using System.ComponentModel;

#region IFruit

namespace Domain.Entity
{
    [PayloadTableForEntity(typeof(IFruit))]
    public static class IFruit_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[]
            {
            };
        }
    }

    public interface IFruitServerHandler : IEntityServerHandler
    {
    }

    public abstract class FruitServerBase : ServerEntity
    {
        public override int TrackableDataCount { get { return 0; } }

        public override ITrackable GetTrackableData(int index)
        {
            return null;
        }

        public override void SetTrackableData(int index, ITrackable trackable)
        {
        }
    }

    public interface IFruitClientHandler : IEntityClientHandler
    {
    }

    public abstract class FruitClientBase : ClientEntity
    {
        public override int TrackableDataCount { get { return 0; } }

        public override ITrackable GetTrackableData(int index)
        {
            return null;
        }

        public override void SetTrackableData(int index, ITrackable trackable)
        {
        }
    }
}

#endregion

#region ISnake

namespace Domain.Entity
{
    [PayloadTableForEntity(typeof(ISnake))]
    public static class ISnake_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[]
            {
            };
        }
    }

    public interface ISnakeServerHandler : IEntityServerHandler
    {
    }

    public abstract class SnakeServerBase : ServerEntity
    {
        public override int TrackableDataCount { get { return 0; } }

        public override ITrackable GetTrackableData(int index)
        {
            return null;
        }

        public override void SetTrackableData(int index, ITrackable trackable)
        {
        }
    }

    public interface ISnakeClientHandler : IEntityClientHandler
    {
    }

    public abstract class SnakeClientBase : ClientEntity
    {
        public override int TrackableDataCount { get { return 0; } }

        public override ITrackable GetTrackableData(int index)
        {
            return null;
        }

        public override void SetTrackableData(int index, ITrackable trackable)
        {
        }
    }
}

#endregion
